services:
  # Service PHP-FPM
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-api-starter
    container_name: laravel-api-starter-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-api-starter-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
